

package es.smartaccess.SealSignSQSService.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.4.1
//
// Created by Quasar Development at 21-10-2014
//
//---------------------------------------------------


import java.util.UUID;


import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class BasicHttpBinding_ISignatureQueueServiceBasic
{
    interface IWcfMethod
    {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging = true;

    IServiceEvents callback;
    public BasicHttpBinding_ISignatureQueueServiceBasic(){}

    public BasicHttpBinding_ISignatureQueueServiceBasic (IServiceEvents callback)
    {
        this.callback = callback;
    }
    public BasicHttpBinding_ISignatureQueueServiceBasic(IServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public BasicHttpBinding_ISignatureQueueServiceBasic(IServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                return new HttpsTransportSE(uri.getHost(), uri.getPort(), uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected ExtendedSoapSerializationEnvelope createEnvelope()
    {
        ExtendedSoapSerializationEnvelope envelope= new ExtendedSoapSerializationEnvelope(ExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,ExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport) throws java.lang.Exception
    {
        return transport.call(methodName, envelope,httpHeaders);
    }


    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,ExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }
    
    public Integer AddQueue(final String name ) throws java.lang.Exception
    {
        return (Integer)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "AddQueue");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="name";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(name!=null?name:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("AddQueueResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return Integer.parseInt(j.toString());
                }
                else if (obj!= null && obj instanceof Integer){
                    return (Integer)obj;
                }
                return null;
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/AddQueue");
    }
    
    public android.os.AsyncTask AddQueueAsync(final String name)
    {
        return executeAsync(new Functions.IFunc< Integer>() {
            public Integer Func() throws java.lang.Exception {
                return AddQueue( name);
            }
        });
    }
    
    public void RemoveQueue(final Integer id ) throws java.lang.Exception
    {
        execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "RemoveQueue");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(id!=null?id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/RemoveQueue");
    }
    
    public android.os.AsyncTask RemoveQueueAsync(final Integer id)
    {
        return executeAsync(new Functions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                RemoveQueue( id);
                return null;
            }
        }) ;
    }
    
    public ArrayOfQueueReference GetQueueReferences( ) throws java.lang.Exception
    {
        return (ArrayOfQueueReference)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetQueueReferences");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ArrayOfQueueReference)getResult(ArrayOfQueueReference.class,__result,"GetQueueReferencesResult",__envelope);
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/GetQueueReferences");
    }
    
    public android.os.AsyncTask GetQueueReferencesAsync()
    {
        return executeAsync(new Functions.IFunc< ArrayOfQueueReference>() {
            public ArrayOfQueueReference Func() throws java.lang.Exception {
                return GetQueueReferences( );
            }
        });
    }
    
    public Integer AddJobFromSpooler(final String queueName,final String owner,final String computerName,final Integer originalJobId,final String jobTitle,final byte[] blob,final String jobMetadata ) throws java.lang.Exception
    {
        return (Integer)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "AddJobFromSpooler");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="queueName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(queueName!=null?queueName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="owner";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(owner!=null?owner:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="computerName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(computerName!=null?computerName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="originalJobId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(originalJobId!=null?originalJobId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="jobTitle";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(jobTitle!=null?jobTitle:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="blob";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(blob!=null?org.kobjects.base64.Base64.encode(blob):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="jobMetadata";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(jobMetadata!=null?jobMetadata:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("AddJobFromSpoolerResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return Integer.parseInt(j.toString());
                }
                else if (obj!= null && obj instanceof Integer){
                    return (Integer)obj;
                }
                return null;
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/AddJobFromSpooler");
    }
    
    public android.os.AsyncTask AddJobFromSpoolerAsync(final String queueName,final String owner,final String computerName,final Integer originalJobId,final String jobTitle,final byte[] blob,final String jobMetadata)
    {
        return executeAsync(new Functions.IFunc< Integer>() {
            public Integer Func() throws java.lang.Exception {
                return AddJobFromSpooler( queueName,owner,computerName,originalJobId,jobTitle,blob,jobMetadata);
            }
        });
    }
    
    public Integer AddJob(final String queueName,final Integer originalJobId,final String jobTitle,final byte[] blob,final String jobMetadata ) throws java.lang.Exception
    {
        return (Integer)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "AddJob");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="queueName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(queueName!=null?queueName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="originalJobId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(originalJobId!=null?originalJobId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="jobTitle";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(jobTitle!=null?jobTitle:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="blob";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(blob!=null?org.kobjects.base64.Base64.encode(blob):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="jobMetadata";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(jobMetadata!=null?jobMetadata:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("AddJobResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return Integer.parseInt(j.toString());
                }
                else if (obj!= null && obj instanceof Integer){
                    return (Integer)obj;
                }
                return null;
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/AddJob");
    }
    
    public android.os.AsyncTask AddJobAsync(final String queueName,final Integer originalJobId,final String jobTitle,final byte[] blob,final String jobMetadata)
    {
        return executeAsync(new Functions.IFunc< Integer>() {
            public Integer Func() throws java.lang.Exception {
                return AddJob( queueName,originalJobId,jobTitle,blob,jobMetadata);
            }
        });
    }
    
    public void SetProcessedJob(final Integer id,final byte[] document ) throws java.lang.Exception
    {
        execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "SetProcessedJob");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(id!=null?id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="document";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(document!=null?org.kobjects.base64.Base64.encode(document):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/SetProcessedJob");
    }
    
    public android.os.AsyncTask SetProcessedJobAsync(final Integer id,final byte[] document)
    {
        return executeAsync(new Functions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                SetProcessedJob( id,document);
                return null;
            }
        }) ;
    }
    
    public void RemoveJob(final Integer id ) throws java.lang.Exception
    {
        execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "RemoveJob");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(id!=null?id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/RemoveJob");
    }
    
    public android.os.AsyncTask RemoveJobAsync(final Integer id)
    {
        return executeAsync(new Functions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                RemoveJob( id);
                return null;
            }
        }) ;
    }
    
    public void ChangeJobOwner(final Integer id,final String newOwner ) throws java.lang.Exception
    {
        execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ChangeJobOwner");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(id!=null?id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="newOwner";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(newOwner!=null?newOwner:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/ChangeJobOwner");
    }
    
    public android.os.AsyncTask ChangeJobOwnerAsync(final Integer id,final String newOwner)
    {
        return executeAsync(new Functions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                ChangeJobOwner( id,newOwner);
                return null;
            }
        }) ;
    }
    
    public ArrayOfJobReference GetPendingJobs(final ArrayOfQueueReference queueReferences,final String owner,final String computerName ) throws java.lang.Exception
    {
        return (ArrayOfJobReference)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://tempuri.org/","queueReferences",new ArrayOfQueueReference().getClass());
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetPendingJobs");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="queueReferences";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(queueReferences!=null?queueReferences:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="owner";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(owner!=null?owner:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="computerName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(computerName!=null?computerName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ArrayOfJobReference)getResult(ArrayOfJobReference.class,__result,"GetPendingJobsResult",__envelope);
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/GetPendingJobs");
    }
    
    public android.os.AsyncTask GetPendingJobsAsync(final ArrayOfQueueReference queueReferences,final String owner,final String computerName)
    {
        return executeAsync(new Functions.IFunc< ArrayOfJobReference>() {
            public ArrayOfJobReference Func() throws java.lang.Exception {
                return GetPendingJobs( queueReferences,owner,computerName);
            }
        });
    }
    
    public ArrayOfJobReference GetProcessedJobs(final ArrayOfQueueReference queueReferences,final String owner,final String computerName ) throws java.lang.Exception
    {
        return (ArrayOfJobReference)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://tempuri.org/","queueReferences",new ArrayOfQueueReference().getClass());
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetProcessedJobs");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="queueReferences";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(queueReferences!=null?queueReferences:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="owner";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(owner!=null?owner:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="computerName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(computerName!=null?computerName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ArrayOfJobReference)getResult(ArrayOfJobReference.class,__result,"GetProcessedJobsResult",__envelope);
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/GetProcessedJobs");
    }
    
    public android.os.AsyncTask GetProcessedJobsAsync(final ArrayOfQueueReference queueReferences,final String owner,final String computerName)
    {
        return executeAsync(new Functions.IFunc< ArrayOfJobReference>() {
            public ArrayOfJobReference Func() throws java.lang.Exception {
                return GetProcessedJobs( queueReferences,owner,computerName);
            }
        });
    }
    
    public Job GetJob(final Integer id ) throws java.lang.Exception
    {
        return (Job)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetJob");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(id!=null?id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (Job)getResult(Job.class,__result,"GetJobResult",__envelope);
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/GetJob");
    }
    
    public android.os.AsyncTask GetJobAsync(final Integer id)
    {
        return executeAsync(new Functions.IFunc< Job>() {
            public Job Func() throws java.lang.Exception {
                return GetJob( id);
            }
        });
    }
    
    public BiometricSignatureContext BeginBiometricSignatureProvider(final Integer idDocument,final Integer signatureIndex,final String queueName,final String biometricId,final String biometricAccount,final String uri,final String providerParameter,final byte[] document ) throws java.lang.Exception
    {
        return (BiometricSignatureContext)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BeginBiometricSignatureProvider");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idDocument";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idDocument!=null?idDocument:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="signatureIndex";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(signatureIndex!=null?signatureIndex:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="queueName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(queueName!=null?queueName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricId";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(biometricId!=null?biometricId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricAccount";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(biometricAccount!=null?biometricAccount:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="uri";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(uri!=null?uri:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="providerParameter";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(providerParameter!=null?providerParameter:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="document";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(document!=null?org.kobjects.base64.Base64.encode(document):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (BiometricSignatureContext)getResult(BiometricSignatureContext.class,__result,"BeginBiometricSignatureProviderResult",__envelope);
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/BeginBiometricSignatureProvider");
    }
    
    public android.os.AsyncTask BeginBiometricSignatureProviderAsync(final Integer idDocument,final Integer signatureIndex,final String queueName,final String biometricId,final String biometricAccount,final String uri,final String providerParameter,final byte[] document)
    {
        return executeAsync(new Functions.IFunc< BiometricSignatureContext>() {
            public BiometricSignatureContext Func() throws java.lang.Exception {
                return BeginBiometricSignatureProvider( idDocument,signatureIndex,queueName,biometricId,biometricAccount,uri,providerParameter,document);
            }
        });
    }
    
    public byte[] EndBiometricSignatureProvider(final UUID instance,final byte[] biometricState,final Integer idDocument,final Integer signatureIndex,final String queueName,final String uri,final String providerParameter ) throws java.lang.Exception
    {
        return (byte[])execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "EndBiometricSignatureProvider");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="instance";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(instance!=null?instance:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricState";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(biometricState!=null?org.kobjects.base64.Base64.encode(biometricState):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idDocument";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idDocument!=null?idDocument:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="signatureIndex";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(signatureIndex!=null?signatureIndex:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="queueName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(queueName!=null?queueName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="uri";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(uri!=null?uri:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="providerParameter";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(providerParameter!=null?providerParameter:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object j = __soap.getProperty("signedDocument");
                return Helper.getBinary(j,false);
            }
        },"http://tempuri.org/ISignatureQueueServiceBasic/EndBiometricSignatureProvider");
    }
    
    public android.os.AsyncTask EndBiometricSignatureProviderAsync(final UUID instance,final byte[] biometricState,final Integer idDocument,final Integer signatureIndex,final String queueName,final String uri,final String providerParameter)
    {
        return executeAsync(new Functions.IFunc< byte[]>() {
            public byte[] Func() throws java.lang.Exception {
                return EndBiometricSignatureProvider( instance,biometricState,idDocument,signatureIndex,queueName,uri,providerParameter);
            }
        });
    }
    protected java.lang.Object execute(IWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        ExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    protected < T> android.os.AsyncTask  executeAsync(final Functions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, OperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected OperationResult< T> doInBackground(Void... params) {
                OperationResult< T> result = new OperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(OperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
   
      

    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,ExtendedSoapSerializationEnvelope envelope)
    {
        if(fault.detail!=null && fault.detail.getChildCount()>0)
        {
            Element detailsNode=(Element)fault.detail.getChild(0);
            try {
                SoapObject exceptionObject=envelope.GetExceptionDetail(detailsNode);
                if(exceptionObject.getName().equals("SealSignDSSFaultContract"))
                {
                    return new SealSignDSSFaultContract(exceptionObject,envelope);
                }
            } catch (java.lang.Exception e) {
                e.printStackTrace();
            }
        }
        return new java.lang.Exception(fault.faultstring);
    }
}


