package es.smartaccess.SealSignSQSService.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.4.1
//
// Created by Quasar Development at 21-10-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.UUID;

public class BiometricSignatureContext extends AttributeContainer implements KvmSerializable,java.io.Serializable
{
    
    public byte[] biometricState;
    
    public UUID instance;

    public BiometricSignatureContext ()
    {
    }

    public BiometricSignatureContext (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("biometricState"))
        {	
            java.lang.Object j = soapObject.getProperty("biometricState");
            this.biometricState = Helper.getBinary(j,false);
        }
        if (soapObject.hasProperty("instance"))
        {	
	        java.lang.Object obj = soapObject.getProperty("instance");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.instance = UUID.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof UUID){
                this.instance = (UUID)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.biometricState!=null?org.kobjects.base64.Base64.encode(this.biometricState):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.instance!=null?this.instance:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "biometricState";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignSQSService";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "instance";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignSQSService";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

	@Override
	public String getInnerText() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setInnerText(String arg0) {
		// TODO Auto-generated method stub
		
	}

}
