package es.smartaccess.SealSignSQSService.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.4.1
//
// Created by Quasar Development at 21-10-2014
//
//---------------------------------------------------



import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.*;
import org.kxml2.io.KXmlParser;
import org.kxml2.kdom.Element;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import org.xmlpull.v1.XmlSerializer;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Vector;
import java.io.StringReader;
import java.io.StringWriter;

public class ExtendedSoapSerializationEnvelope extends SoapSerializationEnvelope {
    public interface IReferenceObject
    {
    }
    static HashMap< java.lang.String,java.lang.Class> classNames = new HashMap< java.lang.String, java.lang.Class>();

    HashMap< java.lang.Object, java.lang.String> reverseReferencesTable = new HashMap< java.lang.Object, java.lang.String>();
    HashMap< java.lang.String, java.lang.Object> referencesTable = new HashMap< java.lang.String, java.lang.Object>();
    private final String MsNs="http://schemas.microsoft.com/2003/10/Serialization/";
    protected static final int QNAME_NAMESPACE = 0;
    private static final String TYPE_LABEL = "type";

    public ExtendedSoapSerializationEnvelope() {
        this(SoapEnvelope.VER11);
    }

    public ExtendedSoapSerializationEnvelope(int soapVersion) {
        super(soapVersion);
        implicitTypes = true;
        setAddAdornments(false);
        new MarshalGuid().register(this);
        new MarshalDateTime().register(this);
        new MarshalFloat().register(this);
    }

    

    @Override
    protected void writeProperty(XmlSerializer writer, java.lang.Object obj, PropertyInfo type) throws IOException {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (obj == null || obj== SoapPrimitive.NullNilElement) {
            writer.attribute(xsi, version >= VER12 ? NIL_LABEL : NULL_LABEL, "true");
            return;
        }
        if(reverseReferencesTable.containsKey(obj))
        {
            java.lang.String id=reverseReferencesTable.get(obj);
            writer.attribute(MsNs, "Ref",id);
            return;
        }
        else
        {
            if(obj instanceof IReferenceObject)
            {
                java.lang.String id=String.format("i%d", reverseReferencesTable.size() + 1);
                reverseReferencesTable.put(obj,id);
                writer.attribute(MsNs, "Id",id);
            }
            java.lang.Object[] qName = getInfo(null, obj);
            if (!type.multiRef && qName[2] == null )
            {
                if (!implicitTypes || (obj.getClass() != type.type && !(obj instanceof Vector ) && type.type!=String.class)) {
                    String xmlName=Helper.getKeyByValue(classNames,obj.getClass());
                    if(xmlName!=null)
                    {
                        java.lang.String[] parts=xmlName.split("\\^\\^");
                        java.lang.String prefix = writer.getPrefix(parts[0], true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" +parts[1]);
                    }
                    else
                    {
                        java.lang.String prefix = writer.getPrefix(type.namespace, true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" + obj.getClass().getSimpleName());
                    }
                }
                //super.writeProperty(writer,obj,type);

                //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
                //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
                writeElement(writer, obj, type, qName[QNAME_MARSHAL]);
            }
            else {
                super.writeProperty(writer, obj, type);
            }
        }
    }

    public SoapObject GetExceptionDetail(Element detailElement) {
         Element errorElement=detailElement.getElement(0);
         return GetSoapObject(errorElement);
    }

    public SoapObject GetSoapObject(Element detailElement) {
        try{
            XmlSerializer xmlSerializer = XmlPullParserFactory.newInstance().newSerializer();
            StringWriter writer = new StringWriter();
            xmlSerializer.setOutput(writer);
            detailElement.write(xmlSerializer);
            xmlSerializer.flush();

            XmlPullParser xpp = new KXmlParser();
            xpp.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, true);

            xpp.setInput(new StringReader(writer.toString()));
            xpp.nextTag();
            SoapObject soapObj = new SoapObject(detailElement.getNamespace(),detailElement.getName());
            readSerializable(xpp,soapObj);
            return soapObj;
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
    }

    public java.lang.Object GetHeader(Element detailElement) {
        if(detailElement.getText(0)!=null)
        {
            SoapPrimitive primitive = new SoapPrimitive(detailElement.getNamespace(),detailElement.getName(),detailElement.getText(0));
            return  primitive;
        }
    
        return GetSoapObject(detailElement);
    }
    
        public void Add(java.lang.String id,java.lang.Object obj)
        {
            if (!referencesTable.containsKey(id))
            {
                referencesTable.put(id, obj);
            }
        }

    public java.lang.Object get(java.lang.Object soap,java.lang.Class cl)
    {
        if(soap==null)
        {
            return null;
        }
        try
        {
            if(soap instanceof  Vector)
            {
                Constructor ctor = cl.getConstructor(java.lang.Object.class,ExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
            java.lang.Object refAttr=Helper.getAttribute((AttributeContainer)soap,"Ref","http://schemas.microsoft.com/2003/10/Serialization/");
            if(refAttr!=null )
            {
                java.lang.String ref=(java.lang.String)refAttr;
                return referencesTable.get(ref);
            }
            else
            {
                if(soap instanceof SoapObject)
                {
                    java.lang.String key=String.format("%s^^%s",((SoapObject)soap).getNamespace(),((SoapObject)soap).getName());
                    if(classNames.containsKey(key))
                    {
                        cl=classNames.get(key);
                    }
                }
                Constructor ctor = cl.getConstructor(java.lang.Object.class,ExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
            return null;
        }
    }
} 

