package es.smartaccess.SealSignSQSService.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.4.1
//
// Created by Quasar Development at 21-10-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class SignatureClientBehaviour extends AttributeContainer implements KvmSerializable,java.io.Serializable
{
    
    public String providerParameter;
    
    public String signatureAccount;
    
    public String signatureId;
    
    public String signatureWindowTitle;
    
    public STUConfiguration stuConfiguration;
    
    public String uri;

    public SignatureClientBehaviour ()
    {
    }

    public SignatureClientBehaviour (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("providerParameter"))
        {	
	        java.lang.Object obj = soapObject.getProperty("providerParameter");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.providerParameter = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.providerParameter = (String)obj;
            }    
        }
        if (soapObject.hasProperty("signatureAccount"))
        {	
	        java.lang.Object obj = soapObject.getProperty("signatureAccount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.signatureAccount = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.signatureAccount = (String)obj;
            }    
        }
        if (soapObject.hasProperty("signatureId"))
        {	
	        java.lang.Object obj = soapObject.getProperty("signatureId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.signatureId = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.signatureId = (String)obj;
            }    
        }
        if (soapObject.hasProperty("signatureWindowTitle"))
        {	
	        java.lang.Object obj = soapObject.getProperty("signatureWindowTitle");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.signatureWindowTitle = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.signatureWindowTitle = (String)obj;
            }    
        }
        if (soapObject.hasProperty("stuConfiguration"))
        {	
	        java.lang.Object j = soapObject.getProperty("stuConfiguration");
	        this.stuConfiguration = (STUConfiguration)envelope.get(j,STUConfiguration.class);
        }
        if (soapObject.hasProperty("uri"))
        {	
	        java.lang.Object obj = soapObject.getProperty("uri");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.uri = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.uri = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.providerParameter!=null?this.providerParameter:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.signatureAccount!=null?this.signatureAccount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.signatureId!=null?this.signatureId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.signatureWindowTitle!=null?this.signatureWindowTitle:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.stuConfiguration!=null?this.stuConfiguration:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.uri!=null?this.uri:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "providerParameter";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignSQSTypes";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "signatureAccount";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignSQSTypes";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "signatureId";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignSQSTypes";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "signatureWindowTitle";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignSQSTypes";
        }
        if(propertyIndex==4)
        {
            info.type = STUConfiguration.class;
            info.name = "stuConfiguration";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignSQSTypes";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "uri";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignSQSTypes";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

	@Override
	public String getInnerText() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setInnerText(String arg0) {
		// TODO Auto-generated method stub
		
	}

}
