package es.smartaccess.SealSignSQSService.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.4.1
//
// Created by Quasar Development at 21-10-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class STUConfiguration extends AttributeContainer implements KvmSerializable,java.io.Serializable
{
    
    public STUButtonDefinition CancelButton;
    
    public byte[] Image;
    
    public STUButtonDefinition OKButton;

    public STUConfiguration ()
    {
    }

    public STUConfiguration (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("CancelButton"))
        {	
	        java.lang.Object j = soapObject.getProperty("CancelButton");
	        this.CancelButton = (STUButtonDefinition)envelope.get(j,STUButtonDefinition.class);
        }
        if (soapObject.hasProperty("Image"))
        {	
            java.lang.Object j = soapObject.getProperty("Image");
            this.Image = Helper.getBinary(j,false);
        }
        if (soapObject.hasProperty("OKButton"))
        {	
	        java.lang.Object j = soapObject.getProperty("OKButton");
	        this.OKButton = (STUButtonDefinition)envelope.get(j,STUButtonDefinition.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.CancelButton!=null?this.CancelButton:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Image!=null?org.kobjects.base64.Base64.encode(this.Image):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.OKButton!=null?this.OKButton:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = STUButtonDefinition.class;
            info.name = "CancelButton";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignSQSTypes";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Image";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignSQSTypes";
        }
        if(propertyIndex==2)
        {
            info.type = STUButtonDefinition.class;
            info.name = "OKButton";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignSQSTypes";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

	@Override
	public String getInnerText() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setInnerText(String arg0) {
		// TODO Auto-generated method stub
		
	}

}
